### ISSUE TITLE
Change SRCH behavior on bootstrapped container

### ISSUE THREAD

**Issue by ghost** [osixia/container-openldap#596]
Hey,

I have this kind of entry that successfully add an inetOrgPerson to my dn :

```
## Alphonse Daudet
dn: cn=adaudet,dc=example,dc=org
changetype: add
objectclass: inetOrgPerson
cn: adaudet
mail: [adaudet@gmail.com](mailto:adaudet@gmail.com)
uid: adaudet2
userpassword: 123a
```

As I make an auth request (through Postman or python-ldap `r2 = requests.get('http://localhost:5000/ldap', auth=HTTPBasicAuth('adaudet@gmail.com', '123a'))`, the BIND is successfull but the SRCH fails as it search for a person and an uid, as you can see in the container log :

```
616d8a57 conn=1015 fd=13 ACCEPT from IP=172.27.0.1:46692 (IP=0.0.0.0:389)
616d8a57 conn=1015 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
616d8a57 conn=1015 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
616d8a57 conn=1015 op=0 RESULT tag=97 err=0 text=
616d8a57 conn=1015 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(?userPrincipalName=adaudet@gmail.com))"
616d8a57 conn=1015 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
616d8a57 conn=1015 op=2 UNBIND
```

So, how may I change the search filter ? Preferably with environment variables than Dockerfile modification as I tried copying these lines in a `\etc\saslauthd.conf` but w/o success :
```
ldap_servers: ldaps://localhost:389
ldap_search_base: dc=example,dc=com
ldap_filter: (mail=%n)
```
Thanks in advance as I'm quite clueless ^^

**Comment by simplyhappydude** [comment]
@MacGros - The problem is that OpenLDAP doesn't support "userPrincipalName" as an attribute.
